#!/usr/bin/env python

"""
    Weld: A Gmail XMPP Gateway
    Copyright (C) 2010 Lance Stout
    This file is part of Weld.

    See the file LICENSE for copying permission.
"""

import os
import sys
import logging
import time
from optparse import OptionParser

import weld


# Setup the command line arguments.
optp = OptionParser()

# Output verbosity options.
optp.add_option('-q', '--quiet', help='set logging to ERROR',
                action='store_const', dest='loglevel',
                const=logging.ERROR, default=logging.INFO)
optp.add_option('-d', '--debug', help='set logging to DEBUG',
                action='store_const', dest='loglevel',
                const=logging.DEBUG, default=logging.INFO)
optp.add_option('-v', '--verbose', help='set logging to COMM',
                action='store_const', dest='loglevel',
                const=5, default=logging.INFO)

# Component name and secret options.
optp.add_option("-c", "--config", help="path to config file. Default: ~/.weldrc",
                dest="config", default="~/.weldrc")

opts, args = optp.parse_args()

# Setup logging.
logging.basicConfig(level=opts.loglevel,
                    format='%(levelname)-8s %(message)s')

# Load configuration data.
config = weld.load_config(os.path.expanduser(opts.config))

xmpp = weld.GmailTransport(config)

if xmpp.connect():
    xmpp.process(threaded=False)
else:
    log.error("Unable to connect.")
